# Generated by Django 2.1.4 on 2019-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190727_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='image',
            field=models.ImageField(blank=True, default='/images/x.jpg', null=True, upload_to='images/'),
        ),
    ]
