# Generated by Django 2.1.4 on 2019-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190727_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogapp',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
